#!/usr/bin/env bash

set -e

declare -A TARGETS

TERRAFORM_DIR="./terraform/assignment"

get_aws_account_id() {
    aws sts get-caller-identity --query Account --output text
}

get_aws_region() {
    aws configure get region
}

get_ecr_url() {
    echo "$(get_aws_account_id).dkr.ecr.$(get_aws_region).amazonaws.com"
}

load_terraform_outputs() {
    IMAGE_NAME=$(terraform -chdir=$TERRAFORM_DIR output -raw ecr_repository_name)
    LAMBDA_NAME=$(terraform -chdir=$TERRAFORM_DIR output -raw lambda_function_name)
}

TARGETS[build_image]="Builds docker image"
build_image() {
    local image_name=$1
    local build_dir="${2:-.}"
    local commit=$(git rev-parse HEAD)

    if [ -z "$image_name" ]; then
        echo "ERROR: Missing required parameter image_name" >&2
        return 1
    fi

    local aws_url="$(get_ecr_url)"

    IMAGE_URI="$aws_url/$image_name:$commit"
    LATEST_URI="$aws_url/$image_name:latest"

    echo "Building $IMAGE_URI"

    docker build \
        --platform linux/arm64 \
        --provenance=false \
        --no-cache \
        -t "$IMAGE_URI" \
        -t "$LATEST_URI" \
        "$build_dir"
}

TARGETS[push_image]="Pushes docker image to ECR"
push_image() {
    local image_name=$1
    local commit=$(git rev-parse HEAD)

    local aws_url="$(get_ecr_url)"

    IMAGE_URI="$aws_url/$image_name:$commit"
    LATEST_URI="$aws_url/$image_name:latest"

    echo "Logging into ECR..."
    aws ecr get-login-password --region "$(get_aws_region)" \
        | docker login --username AWS --password-stdin "$aws_url"

    echo "Pushing $IMAGE_URI"
    docker push "$IMAGE_URI"

    echo "Pushing $LATEST_URI"
    docker push "$LATEST_URI"
}

TARGETS[update_lambda]="Updates Lambda function image"
update_lambda() {
    local image_uri=$1

    echo "Updating Lambda $LAMBDA_NAME with $image_uri"

    aws lambda update-function-code \
        --function-name "$LAMBDA_NAME" \
        --image-uri "$image_uri"

    aws lambda wait function-updated \
        --function-name "$LAMBDA_NAME"
}

TARGETS[deploy]="Build, push, and deploy Lambda"
deploy() {
    if [ -n "$CI" ]; then
        echo "Running in CI, skipping profile setup"
    else
        setup "${AWS_PROFILE:-default}"
    fi

    load_terraform_outputs
    aws_url="$(get_ecr_url)"

    local commit=$(git rev-parse HEAD)
    local image_uri="$aws_url/$IMAGE_NAME:$commit"

    build_image "$IMAGE_NAME" "."
    push_image "$IMAGE_NAME"
    update_lambda "$image_uri"
}

TARGETS[setup]="Setup local environment"
setup() {
    local profile="${AWS_PROFILE:-${1:-default}}"

    echo "Checking AWS profile: $profile"

    if aws configure list-profiles | grep -qx "$profile"; then
        echo "AWS profile '$profile' already exists"
    else
        echo "AWS profile '$profile' does not exist"
        echo "Creating profile..."

        aws configure --profile "$profile"
    fi

    export AWS_PROFILE="$profile"
    echo "Using AWS_PROFILE=$AWS_PROFILE"
    aws sts get-caller-identity
}

TARGETS[help]="Displays usage help for this script"
help() {
    echo "Usage: ./task <target>"
    echo "Available targets:"
    echo
    for target in "${!TARGETS[@]}"; do
        printf "  \033[33m%-12s\033[0m %s\n" "$target" "${TARGETS[$target]}"
    done
}


TARGET="$1"

if [[ -n "$TARGET" && -n "${TARGETS[$TARGET]}" ]]; then
    shift
    "$TARGET" "$@"
else
    help
    exit 1
fi

